# Generated by Django 5.2.9 on 2026-01-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_extrauserinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserinfo',
            name='bio',
            field=models.TextField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extrauserinfo',
            name='profile_pic',
            field=models.ImageField(default=None, null=True, upload_to='avatars/'),
        ),
    ]
